---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: manager
    component: database
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: 5432
      targetPort: 5432
