apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: database-service
  replicas: 1
  selector:
    matchLabels:
      app: manager
      component: database
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: manager
        component: database
    spec:
      containers:
        - name: database
          image: "{{ index .Values.parameters "database" "image" }}:{{ index .Values.parameters "database" "tag" }}"
          ports:
            - containerPort: 5432
              name: tcp
              protocol: TCP
          envFrom:
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secrets
          volumeMounts:
            - name: database-data
              mountPath: /var/lib/postgresql/data
          imagePullPolicy: IfNotPresent
  volumeClaimTemplates:
    - metadata:
        name: database-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
