// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Infrastructure.Configs;

#nullable disable

namespace Server.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250805173158_Changes")]
    partial class Changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Domain.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Server.Domain.Models.Configuration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Server.Domain.Models.Policy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistryKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegistryKeyType")
                        .HasColumnType("integer");

                    b.Property<string>("RegistryPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegistryValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("Server.Domain.Models.PolicyInConfiguration", b =>
                {
                    b.Property<long>("ConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint");

                    b.Property<string>("RegistryValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConfigurationId", "PolicyId");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyInConfiguration");
                });

            modelBuilder.Entity("Server.Domain.Models.Process", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("Server.Domain.Models.ProcessInConfiguration", b =>
                {
                    b.Property<long>("ConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessId")
                        .HasColumnType("bigint");

                    b.HasKey("ConfigurationId", "ProcessId");

                    b.HasIndex("ProcessId");

                    b.ToTable("ProcessInConfiguration");
                });

            modelBuilder.Entity("Server.Domain.Models.Agent", b =>
                {
                    b.HasOne("Server.Domain.Models.Configuration", "Configuration")
                        .WithMany("Agents")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("Server.Domain.Models.PolicyInConfiguration", b =>
                {
                    b.HasOne("Server.Domain.Models.Configuration", "Configuration")
                        .WithMany("Policies")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Domain.Models.Policy", "Policy")
                        .WithMany("Configurations")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Server.Domain.Models.ProcessInConfiguration", b =>
                {
                    b.HasOne("Server.Domain.Models.Configuration", "Configuration")
                        .WithMany("Processes")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Domain.Models.Process", "Process")
                        .WithMany("Configurations")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("Server.Domain.Models.Configuration", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Policies");

                    b.Navigation("Processes");
                });

            modelBuilder.Entity("Server.Domain.Models.Policy", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("Server.Domain.Models.Process", b =>
                {
                    b.Navigation("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
