---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-server-api-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: manager
      component: manager-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: manager
        component: manager-api
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z database-service 5432; do
                echo "Waiting for database..."
                sleep 2
              done
              echo "Database is up"
      containers:
        - name: manager-server-api
          image: "{{ index .Values.parameters "server-api" "image" }}:{{ index .Values.parameters "server-api" "tag" }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: manager-server-api-secrets

