---
apiVersion: v1
kind: Secret
metadata:
  name: manager-server-api-secrets
  labels:
    app: manager
    component: manager-api
stringData:
  ConnectionStrings__DefaultConnection: "Host=database-service;Port=5432;Username=postgres;Password={{ .Values.secrets.database.POSTGRES_PASSWORD }};Database=Manager"
  JwtSettings__Secret: "{{ index .Values.secrets "server-api" "JwtSettings__Secret" }}"
  JwtSettings__Issuer: "{{ index .Values.secrets "server-api" "JwtSettings__Issuer" }}"
  JwtSettings__Audience: "{{ index .Values.secrets "server-api" "JwtSettings__Audience" }}"
  JwtSettings__ExpiryMinutes: "{{ index .Values.secrets "server-api" "JwtSettings__ExpiryMinutes" }}"
type: Opaque
