---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-server-ui-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: manager
      component: manager-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: manager
        component: manager-ui
    spec:
      containers:
        - name: manager-server-ui
          image: "{{ index .Values.parameters "server-ui" "image" }}:{{ index .Values.parameters "server-ui" "tag" }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: manager-server-ui-config
