---
apiVersion: v1
kind: Service
metadata:
  name: manager-server-ui-service
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: manager
    component: manager-ui
  ports:
  - name: "http"
    protocol: "TCP"
    port: 80
    targetPort: 80
