name: Build and Push Server.Ui Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check files presence
        run: |
          ls -la src/Server/Server.Ui/

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --prefix src/Server/Server.Ui

      - name: Build Server.Ui
        run: npm run build --prefix src/Server/Server.Ui

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/Server/Server.Ui/Dockerfile
          push: true
          tags: vitaliipriadilia/server.ui:${{ github.event.inputs.version }}
